en:
  greeting_message: "Hello"
  farewell_message: "Bye"
  start_menu_message: "<i>Choose that you want</i>"
  thanks: "Thanks"
  signin: "Start"
  settings: "Settings"
  hide_menu: "[Hide menu]"
  add_user_login: "Enter your <b>LOGIN</b> (email/phone)"
  add_user_password: "Enter you <b>PASSWORD</b>"
  not_correct_email: "This is not email."
  error: "Error."
  auth_failed: "Not correct email or password."
  try_again: "Try again"
  greetings: "Welcome"
  auth_success: "Authorization succeed"
  not_correct_data_input: "Not correct data input."
  teachbase: "Teachbase"
  retry: "Retry connection"
  courses_active: "active"
  courses_archived: "archived"
  average_score_percent: "Summary average score in your profile"
  total_time_spent: "Total time spent by learning"
  courses: "Courses"
  hour: "h."
  minute: "min."
  profile_state: "Your profile progress"
  show_profile_state: "Profile"
  need_auth: "You must be authorized"
  for_profile: "for profile"
  stage_empty: "It's just empty now"
  enter: "Authorization"
  courses_list: "Courses list"
  show_course_list: "Show course list"
  course: "Course"
  open: "Open"
  course_results: "Results"
  deadline: "Deadline"
  progress: "Progress"
  started_at: "Started at"
  success: "Successful"
  status: "Complete status"
  success_true: "Success"
  success_false: "Failed"
  status_active: "Active"
  status_archived: "Archived"
  section: "Section"
  section2: "section"
  section_show_hint: "For example *[id:1]* - will open section №1"
  in: "in"
  information: "Information"
  course_sections: "Sections"
  update_data: "Update"
  updating_data: "Updating"
  updating_success: "Updated succeful"
  section_unable: "Do previosly sections first"
  section_delayed: "Section is unable. Will be open at:"
  section_unpublish: "This section is unpublish now"
  material: "Material"
  empty: "Nothing is here"
  courses_update: "Update courses list"
  sign_out: "Exit"
  unexpected_error: "Unexpected error"
  scenario: "Study mode"
  base: "Base"
  localization: "Localization"
  show_all: "Show all"
  show_avaliable: "Show avaliable"
  show_unvaliable: "Show unvaliable"
  from: "from"
  avaliable: "Avaliable"
  section3: "sections"
  find_by_query_num: "Find by №"
  enter_the_number: "Enter the number"
  edit: "Edit"
  editing_settings: "Editing settings"
  editted: "Editted"
  standart_learning: "Standart"
  marathon: "Marathon"
  ru: "Russian"
  en: "English"
  choose_localization: "Choose localization"
  choose_scenario: "Choose study mode"
  back: "Back"
  show_more: "Show more"
  courses2: "courses"
  materials: "Material"
  tasks: "Task"
  quizzes: "Quiz"
  scorm_packages: "SCORM"
  content: "Content"
  open: "Open"
  back_to: "Back to"
  approve: "Approve"
  view: "View"
  viewed: "Viewed"
  send: "Send"
  answer: "Answer"
  task: "Task"
  attachments: "Attachments"
  enter_your_answer: "Enter your answer"
  confirm_action: "Confirm this action"
  accept: "Accept"
  decline: "Decline"
  accepted: "Accepted"
  declined: "Declined"
ru: 
  greeting_message: "Привет,"
  farewell_message: "Пока"
  start_menu_message: "<i>Что делаем дальше?</i>"
  thanks: "Спасибо"
  signin: "Старт"
  settings: "Настройки"
  hide_menu: "[Скрыть меню]"
  add_user_login: "Введите ваш <b>ЛОГИН</b> (email/номер телефона)"
  add_user_password: "Введите ваш <b>ПАРОЛЬ</b>"
  not_correct_email: "Это не email."
  error: "Ошибка."
  auth_failed: "Неправильный логин или пароль."
  try_again: "Попробуйте еще раз"
  greetings: "Добро пожаловать"
  auth_success: "Вход выполнен успешно"
  not_correct_data_input: "Введены неверные данные."
  teachbase: "Teachbase"
  retry: "Попытка подключения"
  courses_active: "на изучении"
  courses_archived: "завершенные"
  average_score_percent: "Успешность прохождения всех курсов"
  total_time_spent: "Общее время прохождения курсов"
  courses: "Курсы"
  hour: "ч."
  minute: "мин."
  profile_state: "Прогресс твоего профиля"
  show_profile_state: "Профайл"
  need_auth: "Требуется авторизация"
  for_profile: "профиля"
  stage_empty: "Пока что здесь пусто"
  enter: "Войти"
  courses_list: "Список курсов"
  show_course_list: "Показать список курсов"
  course: 'Курс'
  open: "Перейти"
  course_results: "Результаты"
  deadline: "Дата окончания"
  progress: "Прогресс"
  started_at: "Дата начала"
  success: "Успешность"
  status: "Статус завершенности"
  success_true: "Успешно"
  success_false: "Не успешно"
  status_active: "На изучении"
  status_archived: "Завершен"
  section: "Часть"
  section2: "части"
  section_show_hint: "Например, [id:1] - открыть Часть №1"
  in: "в"
  information: "Информация"
  course_sections: "Содержание"
  update_data: "Обновить данные"
  updating_data: "Обновление данных"
  updating_success: "Данные обновлены успешно"
  section_unable: "Станет доступна после прохождения предыдущих частей"
  section_delayed: "Доступ откроется:"
  section_unpublish: "Не опубликована"
  material: "Материал"
  empty: "Здесь ничего нет"
  courses_update: "Обновить список курсов"
  sign_out: "Выход"
  unexpected_error: "Неожиданная ошибка"
  scenario: "Режим обучения"
  base: "Базовый"
  localization: "Язык"
  show_all: "Показать все"
  show_avaliable: "Доступные"
  show_unvaliable: "Не доступные"
  from: "из"
  avaliable: "Доступно"
  section3: "частей"
  find_by_query_num: "Найти по №"
  enter_the_number: "Введите номер"
  edit: "Изменить"
  editing_settings: "Изменение настроек"
  editted: "Изменено"
  standart_learning: "Обычный"
  marathon: "Марафон"
  ru: "Русский"
  en: "Английский"
  choose_localization: "Выберите язык интерфейса"
  choose_scenario: "Выберите режим обучения"
  back: "Назад"
  show_more: "Показать еще"
  courses2: "курсов"
  materials: "Материал"
  tasks: "Задание"
  quizzes: "Тест"
  scorm_packages: "SCORM задание"
  content: "Контент"
  open: "Открыть"
  back_to: "Вернуться к"
  approve: "Подтвердить"
  view: "Просмотр"
  viewed: "Просмотрено"
  send: "Отправить"
  answer: "Ответ"
  task: "Задание"
  attachments: "Вложения"
  enter_your_answer: "Введите ваш ответ"
  confirm_action: "Подтвердите действие"
  accept: "Подтвердить"
  decline: "Отменить"
  accepted: "Подтверждено"
  declined: "Отменено"