en:
  greeting_message: "Hello"
  farewell_message: "Bye"
  start_menu_message: "Choose that you want"
  thanks: "Thanks"
  signin: "Start"
  settings: "Settings"
  hide_menu: "[Hide menu]"
  add_user_email: "Enter your *EMAIL*"
  add_user_password: "Enter you *PASSWORD*"
  not_correct_email: "This is not email."
  error: "Error."
  auth_failed: "Not correct email or password."
  try_again: "Try again"
  greetings: "Welcome"
  auth_success: "Authorization succeed"
  not_correct_data_input: "Not correct data input."
  in_teachbase: "in Teachbase"
  retry: "Retry connection"
  active_courses: "active"
  archived_courses: "archived"
  average_score_percent: "Summary average score in your profile"
  total_time_spent: "Total time spent by learning"
  courses: "Courses"
  hour: "h."
  minute: "min."
  profile_state: "Your profile progress"
  show_profile_state: "Profile"
  need_auth: "You must be authorized"
  for_profile: "for profile"
  stage_empty: "It's just empty now"
  enter: "Authorization"
  course_list_l1: "Courses list"
  show_course_list: "Show course list"
  course: "Course"
  open: "Open"
  course_results: "Results"
  deadline: "Deadline"
  progress: "Progress"
  started_at: "Started at"
  success: "Successful"
  complete_status: "Complete status"
  success_true: "Success"
  success_false: "Failed"
  complete_status_active: "Active"
  complete_status_archived: "Archived"
  section: "Section"
ru: 
  greeting_message: "Привет"
  farewell_message: "Пока"
  start_menu_message: "Что делаем?"
  thanks: "Спасибо"
  signin: "Старт"
  settings: "Настройки"
  hide_menu: "[Скрыть меню]"
  add_user_email: "Введите ваш *EMAIL*"
  add_user_password: "Введите ваш *ПАРОЛЬ*"
  not_correct_email: "Это не email."
  error: "Ошибка."
  auth_failed: "Неправильный логин или пароль."
  try_again: "Попробуйте еще раз"
  greetings: "Добро пожаловать"
  auth_success: "Вход выполнен успешно"
  not_correct_data_input: "Введены неверные данные."
  in_teachbase: "в Teachbase"
  retry: "Попытка подключения"
  active_courses: "на изучении"
  archived_courses: "завершенные"
  average_score_percent: "Успешность прохождения всех курсов"
  total_time_spent: "Общее время прохождения курсов"
  courses: "Курсы"
  hour: "ч."
  minute: "мин."
  profile_state: "Прогресс твоего профиля"
  show_profile_state: "Профайл"
  need_auth: "Требуется авторизация"
  for_profile: "профиля"
  stage_empty: "Пока что здесь пусто"
  enter: "Войти"
  course_list_l1: "Список курсов"
  show_course_list: "Показать список курсов"
  course: 'Курс'
  open: "Перейти"
  course_results: "Результаты"
  deadline: "Дата окончания"
  progress: "Прогресс"
  started_at: "Дата начала"
  success: "Успешность"
  complete_status: "Статус завершенности"
  success_true: "Успешно"
  success_false: "Не успешно"
  complete_status_active: "На изучении"
  complete_status_archived: "Завершен"
  section: "Часть"